---
# ################
# Playbook control
# ################

# Take the package given by the OS/distrib
rabbitmq_os_package: true

# Plugins
rabbitmq_plugins: [rabbitmq_management]
rabbitmq_new_only: 'no'

# VHOST
rabbitmq_vhost_definitions: 
  - name:    devmobsters
rabbitmq_users_definitions:
  - vhost:    devmobsters
    user:     lvl6client
    password: devclient
  - vhost:    devmobsters
    user:     lvl6server
    password: devserver
  - vhost:    devmobsters
    user:     lvl6api
    password: devapi
    tags:                # Optionnal, user tags
    - monitoring
    - management



# Avoid setting up federation
rabbitmq_federation: false

# defaults file for rabbitmq
rabbitmq_cacert     : "ca/cacert.pem"
rabbitmq_server_key : "server/key.pem"
rabbitmq_server_cert: "server/cert.pem"
rabbitmq_ssl        : true

# ######################
# RabbitMQ Configuration
# ######################

# rabbitmq TCP configuration
rabbitmq_conf_tcp_listeners_address: '0.0.0.0'
rabbitmq_conf_tcp_listeners_port: 5672

# rabbitmq SSL configuration
rabbitmq_conf_ssl_listeners_address           : '0.0.0.0'
rabbitmq_conf_ssl_listeners_port              : 5671
rabbitmq_conf_ssl_options_cacertfile          : "/etc/rabbitmq/ssl/{{ rabbitmq_cacert | basename }}"
rabbitmq_conf_ssl_options_certfile            : "/etc/rabbitmq/ssl/{{ rabbitmq_server_cert | basename }}"
rabbitmq_conf_ssl_options_keyfile             : "/etc/rabbitmq/ssl/{{ rabbitmq_server_key | basename }}"
rabbitmq_conf_ssl_options_fail_if_no_peer_cert: "false"

rabbitmq_env: false
