---
- name: Restart monit
  service:
    name=monit
    enabled=yes state=restarted
  sudo: yes

- name: Restart elasticsearch
  service:
    name=elasticsearch
    state=restarted
  sudo: yes

- name: Restart logstash
  service:
    name=logstash
    state=restarted
  sudo: yes

- name: Restart nginx
  service:
    name=nginx
    state=restarted
  sudo: yes

- name: Restart supervisor
  service:
    name=supervisor
    enabled=yes state=restarted
  sudo: yes

- name: Restart kibana
  supervisorctl:
    name=kibana
    state=restarted
  sudo: yes
