
- name: Update /etc/security/limits.conf file (1/2)
  sudo: yes
  lineinfile: dest=/etc/security/limits.conf 
              insertbefore='# End of file'
              line='*             soft    nofile          {{rabbit_file_descriptors}}'
              state=present

- name: Update /etc/security/limits.conf file (2/2)
  sudo: yes
  lineinfile: dest=/etc/security/limits.conf 
              insertbefore='# End of file'
              line='*             hard    nofile          {{rabbit_file_descriptors}}'
              state=present

- name: Update /etc/pam.d/su file  
  sudo: yes
  lineinfile: dest=/etc/pam.d/su 
              regexp="^session    required   pam_limits.so" 
              insertafter='^# session    required   pam_limits.so'
              line="session    required   pam_limits.so"
              state=present

- name: Update /etc/default/rabbitmq-server file  
  sudo: yes
  lineinfile: dest=/etc/default/rabbitmq-server
              regexp="^ulimit -n " 
              line="ulimit -n {{rabbit_file_descriptors}}"
              state=present

