

#Copy SSL Certs 

- name: Synchronize rabbit certs
  synchronize: src=rabbitmq dest=/etc/rabbitmq owner=root group=root mode=0755 recursive=yes

- name: Synchronize aws credentials
  synchronize: src=.aws dest=/root/ owner=root group=root mode=0755 recursive=yes


- name: Synchronize cloudwatch scripts for rabbitmq
  synchronize: src=rabbitmq-cloudwatch dest=/root/ owner=root group=root mode=0755 recursive=yes



- name: Install system packages (apt version)
  apt: pkg={{ item }} state=latest
  with_items:
    - python-pip
    - rabbitmq-server
    - cloud-utils


- name: Install boto Python library
  pip: name=boto state=latest


- name: Install AWS CLI
  pip: name=awscli state=latest



#cron for rabbit cloudwatch TODO: extract hostname and node name
- name: RabbitMQ Cloudwatch Cron
  cron: name="rabbitmq-cloudwatch" job="./getRabbitMQNodeInfo.sh -r "http://{{inventory_hostname}}:15672/api" -u {{rabbit_api_user}} -p {{rabbit_api_pass}} -n rabbit@{{inventory_hostname_short}}" state=present

