---
# Install dependancies
- apt: name=python-pip state=present
 
# Install Curator
- pip: name=elasticsearch-curator
 
- name: remove old curator crontab
  file: path=/etc/cron.d/{{ item }} state=absent
  tags: [cron]
  with_items:
    - 'curator'
    - 'curator_clean'
    - 'curator_close'
    - 'curator_delete'
  sudo: yes 

- name: install curator crontab
  cron: name='curator_delete'
        minute='0' hour='10'
        user='root'
        job='/usr/local/bin/curator --host localhost delete indices --time-unit days --timestring "\%Y.\%m.\%d" --older-than {{ curator_max_keep_days | default(360) }}'
        cron_file='curator_delete'
        state='present'
  tags: [cron]
  sudo: yes

 
- name: install curator crontab
  cron: name='curator_close'
        minute='45' hour='9'
        user='root'
        job='/usr/local/bin/curator --host localhost close indices --time-unit days --timestring "\%Y.\%m.\%d" --older-than {{ curator_close_after_days | default(14) }}'
        cron_file='curator_close'
        state='present'
  tags: [cron]
  sudo: yes
