---
- name: ES apt repo
  apt_repository:
    repo="deb http://packages.elasticsearch.org/elasticsearch/{{ elk_elasticsearch.version }}/{{ ansible_os_family|lower }} stable main"
    update_cache=yes
  when: ansible_os_family == 'Debian'
  sudo: yes

- name: Install ES apt packages
  apt: pkg=elasticsearch update_cache=yes state=latest
  sudo: yes
  when: ansible_os_family == 'Debian'
  notify: Restart elasticsearch

- name: See if cloud-aws is installed
  shell: "[ -d /usr/share/elasticsearch/plugins/cloud-aws ] && echo 'Found' || echo ''"
  register: cloud_aws_installed

- name: Install cloud-aws plugin
  shell: /usr/share/elasticsearch/bin/plugin install elasticsearch/elasticsearch-cloud-aws/2.6.0
  sudo: yes
  when: (not cloud_aws_installed.stdout)
  notify: Restart elasticsearch

- name: Curator PIP package
  pip: name=elasticsearch-curator state=latest
  sudo: yes

- name: Create elasticsearch data dir
  file: path=/mnt/elk state=directory owner=elasticsearch group=elasticsearch mode=0755
  sudo: yes

- name: ES config file
  template:
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root group=root mode=644
  sudo: yes
  notify: Restart elasticsearch

- name: Make monit to look after ES
  template:
    src=elasticsearch.monitrc.conf.j2
    dest=/etc/monit/conf.d/elasticsearch.monitrc.conf
    owner=root group=root mode=644
  sudo: yes
  notify: Restart monit

- name: Stop Monit
  service: name=monit state=stopped
